state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

move_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50
    left_wheel: 'left_wheel_joint'
    right_wheel: 'right_wheel_joint'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

simon_arm_controller:
    type: "velocity_controllers/JointPositionController"
    joint: simon_arm_joint
    pid: {p: 1,  d: 0, i: 0, i_clamp: 1}

rope_controller:
    type: "velocity_controllers/JointVelocityController"
    joint: rope_joint

