#footprint: [[0.15, 0.1], [0.15, -0.1], [-0.15, -0.1], [-0.15, 0.1]]
robot_radius: 0.2
inflation_radius: 0.15
transform_tolerance: 0.5

obstacle_range: 2.5
raytrace_range: 3.0

observation_sources: front_lidar 

front_lidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

