off_ramp: 
    position: 
        x: -5.5
        y: 5.5
        z: 0.0
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.914514367404
        w: 0.404553422692

bottom_of_ramp:
    position:
        x: -4.791
        y:  4.840
        z:  0.000
    orientation:
        x:  0.000
        y:  0.000
        z:  0.928
        w:  0.372

